import React from "react";
import { useState } from "react";
import img from "../Asset/Somnath/somnath.jpg";
import img2 from "../Asset/Somnath/2.jpg";
import img3 from "../Asset/Somnath/3.jpg";
import img4 from "../Asset/Somnath/4.jpg";
import img1869 from "../Asset/Somnath/1869.jpg";
import img1896 from "../Asset/Somnath/1896.jpg";

const Somnath = () => {

    const [english, setEnglish] = useState(true);
    const [hindi, setHindi] = useState(false);
    const [gujrati, setGujarati] = useState(false);
    const [image, setImage] = useState(false);

    const onButtonClickEnglish = () => {
        setEnglish(true);
        setHindi(false);
        setGujarati(false);
        setImage(false);
    }

    const onButtonClickHindi = () => {
        setEnglish(false);
        setHindi(true);
        setGujarati(false);
        setImage(false);
    }

    const onButtonClickGujrati = () => {
        setEnglish(false);
        setHindi(false);
        setGujarati(true);
        setImage(false);
    }

    const onButtonClickImage = () => {
        setEnglish(false);
        setHindi(false);
        setGujarati(false);
        setImage(true);
    }

    return (
        <>
            <div className="space-y-4 overflow-auto h-screen">
                <div className="flex justify-center w-full">
                    <h1 className="text-xl font-bold border-2 p-2 rounded-md">Somnath Jyotirling Temple</h1>
                </div>
                <div>
                    <img src={img} alt="" />
                </div>
                <h1 className="text-xl font-bold">History Of Somnath Temple</h1>
                <div className="flex gap-5 xsm:gap-2">
                    <button onClick={onButtonClickEnglish} className="border-2 border-gray-400 rounded-md p-2">English</button>
                    <button onClick={onButtonClickHindi} className="border-2 border-gray-400 rounded-md p-2">Hindi</button>
                    <button onClick={onButtonClickGujrati} className="border-2 border-gray-400 rounded-md p-2">Gujrati</button>
                    <button onClick={onButtonClickImage} className="border-2 border-gray-400 rounded-md p-2">Images</button>
                </div>
                {english && (
                    <div className="flex flex-col space-y-3">
                        <div>
                            <p>The Somanath temple (IAST: somanātha) or Deo Patan, is a Hindu temple located in Prabhas Patan, Veraval in Gujarat, India. It is one of the most sacred pilgrimage sites for Hindus and is the first among the twelve jyotirlinga shrines of Shiva.It is unclear when the first version of the Somnath temple was built, with estimates varying between the early centuries of the 1st millennium and about the 9th century CE.The temple is not mentioned in ancient Sanskrit texts of Hinduism as Somnath nomenclature, but the "Prabhasa-Pattana" (Prabhas Patan) is mentioned as a tirtha (pilgrimage site), where this temple exists.For example, the Mahabharata in Chapters 109, 118, and 119 of Book 3 (Vana Parva), and Sections 10.45 and 10.78 of the Bhagavata Purana state Prabhasa to be a tirtha on the coastline of Saurashtra.</p>
                            <p>The temple was reconstructed several times in the past after repeated destruction by multiple Muslim invaders and rulers, notably starting with an attack by Mahmud Ghazni in the 11th century.</p>
                            <p>In the late 19th and early 20th centuries, historians and archaeologists of the colonial era actively studied the Somnath temple because its ruins showed a historic Hindu temple that was turning into an Islamic mosque.After India's independence, those ruins were demolished, and the present Somnath temple was reconstructed in the Māru-Gurjara style of Hindu temple architecture. The contemporary Somnath temple's reconstruction was started under the orders of the first Deputy Prime Minister of India, Vallabhbhai Patel after receiving approval for reconstruction from Mahatma Gandhi. The reconstruction was completed in May 1951, after his death.</p>
                        </div>
                        <div>
                            <h1 className="text-xl font-bold">Location</h1>
                            <p>The Somnath temple is located along the coastline in Prabhas Patan, Veraval, Saurashtra region of Gujarat. It is about 400 kilometres (249 mi) southwest of Ahmedabad, 82 kilometres (51 mi) south of Junagadh – another major archaeological and pilgrimage site in Gujarat. It is about 7 kilometres (4 mi) southeast of the Veraval railway junction, about 130 kilometres (81 mi) southeast of the Porbandar airport and about 85 kilometres (53 mi) west of the Diu airport.</p>
                            <p>The Somnath temple is located close to the ancient trading port of Veraval, one of three in Gujarat from where Indian merchants departed to trade goods. The 11th-century Persian historian Al-Biruni states that Somnath has become so famous because "it was the harbor for seafaring people and a station for those who went to and fro between Sufala in the country of Zanj (east Africa) and China". Combined with its repute as an eminent pilgrimage site, its location was well known to the kingdoms within the Indian subcontinent.[17][18] Literature and epigraphical evidence suggest that the medieval-era Veraval port was also actively trading with the Middle East and Southeast Asia. This brought wealth and fame to the Veraval area, as well as the temple.</p>
                            <p>The site of Prabhas Patan was occupied during the Indus Valley Civilisation, 2000–1200 BCE. It was one of very few sites in the Junagadh district to be so occupied. After abandonment in 1200 BCE, it was reoccupied in 400 BCE and continued into the historical period. Prabhas is also close to the other sites similarly occupied: Junagadh, Dwarka, Padri and Bharuch.</p>
                        </div>
                        <div>
                            <h1 className="text-xl font-bold">Nomenclature and significance</h1>
                            <p>Somnath means "Lord of the Soma" or "moon".[note 1] The site is also called Prabhasa ("place of splendor").Somnath temple has been a jyotirlinga site for the Hindus, and a holy place of pilgrimage (tirtha ). It is one of five most revered sites on the seacoast of India, along with the nearby Dvaraka in Gujarat, Puri in Odisha, Rameshvaram and Chidambaram in Tamil Nadu.</p>
                        </div>
                        <div>
                            <h1 className="text-xl font-bold">Jyotirlinga</h1>
                            <p>Many Hindu texts provide a list of the most sacred Shiva pilgrimage sites, along with a guide for visiting the site. The best known were the Mahatmya genre of texts. Of these, Somnatha temple tops the list of jyotirlingas in the Jnanasamhita – chapter 13 of the Shiva Purana, and the oldest known text with a list of jyotirlingas. Other texts include the Varanasi Mahatmya (found in Skanda Purana), the Shatarudra Samhita and the Kothirudra Samhita.All either directly mention the Somnath temple as the number one of twelve sites, or call the top temple as "Somesvara" in Saurashtra – a synonymous term for this site in these texts.The exact date of these texts is unknown, but based on references they make to other texts and ancient poets or scholars, these have been generally dated between the 10th- and 12th-century, with some dating it much earlier and others a bit later.</p>
                        </div>
                        <div>
                            <h1 className="text-xl font-bold">Scriptural mentions</h1>
                            <p>The Somnath temple is not mentioned in ancient Sanskrit texts of Hinduism, but the "Prabhasa-Pattana" is mentioned as a tirtha. For example, the Mahabharata in Chapters 109, 118 and 119 of the Book Three (Vana Parva), and Sections 10.45 and 10.78 of the Bhagavata Purana state Prabhasa to be a tirtha on the coastline of Saurashtra.</p>
                            <p>Alf Hiltebeitel – a Sanskrit scholar known for his translations and studies on Indic texts including the Mahabharata, states that the appropriate context for the legends and mythologies in the Mahabharata are the Vedic mythologies which it borrowed, integrated and re-adapted for its times and its audience.[31] The Brahmana layer of the Vedic literature already mention tirtha related to the Saraswati river. However, given the river was nowhere to be seen when the Mahabharata was compiled and finalized, the Saraswati legend was modified. It vanishes into an underground river, then emerges as an underground river at holy sites for sangam (confluence) already popular with the Hindus. The Mahabharata then integrates the Saraswati legend of the Vedic lore with the Prabhasa tirtha, states Hiltebeitel.[31] The critical editions of the Mahabharata, in several chapters and books mentions that this "Prabhasa" is at a coastline near Dvaraka. It is described as a sacred site where Arjuna and Balarama go on tirtha, a site where Lord Krishna chooses to go and spends his final days, then dies.</p>
                            <p>Catherine Ludvik – a Religious Studies and Sanskrit scholar, concurs with Hiltebeitel. She states that the Mahabharata mythologies borrow from the Vedic texts but modify them from Brahmin-centered "sacrificial rituals" to tirtha rituals that are available to everyone – the intended audience of the great epic.[32] More specifically, she states that the sacrificial sessions along the Saraswati river found in sections such as of Pancavimsa Brahmana were modified to tirtha sites in the context of the Saraswati river in sections of Vana Parva and Shalya Parva.[32] Thus the mythology of Prabhasa in the Mahabharata, which it states to be "by the sea, near Dwaraka". This signifies an expanded context of pilgrimage as a "Vedic ritual equivalent", integrating Prabhasa that must have been already important as a tirtha site when the Vana Parva and Shalya Parva compilation was complete</p>
                            <p>The 5th-century poem Raghuvamsa of Kalidasa mentions some of revered Shiva pilgrimage sites of his times. It includes Banaras (Varanasi), Mahakala-Ujjain, Tryambaka, Prayaga, Pushkara, Gokarna and Somnatha-Prabhasa. This list of Kalidasa gives a "clear indication of tirthas celebrated in his day", states Diana Eck – an Indologist known for her publications on historic Indian pilgrimage sites.</p>
                        </div>
                        <div>
                            <h1 className="text-xl font-bold">History</h1>
                            <p>The site of Somnath has been a pilgrimage site from ancient times on account of being a Triveni Sangam (the confluence of three rivers: Kapila, Hiran and Saraswati). Soma, the Moon god, is believed to have lost his lustre due to a curse, and he bathed in the Sarasvati River at this site to regain it. The result is said to be the waxing and waning of the moon. The name of the town, Prabhas, meaning lustre, as well as the alternative names Someshvar and Somnath ("the lord of the moon" or "the moon god"), arise from this tradition.</p>
                            <p>The name Someshvara begins to appear starting in the 9th century. The Gurjara-Pratihara king Nagabhata II (r. 805–833) recorded that he has visited tirthas in Saurashtra, including Someshvara.[36] Romila Thapar states that this does not imply the existence of a temple, but rather that it was a pilgrimage site (tirtha). The Chaulukya (Solanki) king Mularaja possibly built the first temple for Soma at the site sometime before 997 CE, even though some historians believe that he may have renovated a smaller earlier temple.</p>
                            <p>The post-1950 excavations of the Somnath site have unearthed the earliest known version of the Somnath temple. The excavations showed the foundations of a 10th-century temple, notable broken parts and details of a major, well decorated version of a temple. Madhusudan Dhaky believes it to have been the one that was destroyed by Mahmud of Ghazni.B.K. Thapar, the archaeologist who did the excavation, stated that there was definitely a temple structure at Somnath-Patan in the 9th-century, but none before.</p>
                            <p>In 1026, during the reign of Bhima I, the Turkic Muslim ruler Mahmud of Ghazni raided and plundered the Somnath temple, broke its jyotirlinga. He took away a booty of 20 million dinars.[42][8] According to Romila Thapar, relying on a 1038 inscription of a Kadamba king of Goa, the condition of Somnath temple in 1026 after Ghazni's is unclear because the inscription is "puzzlingly silent" about Ghazni's raid or temple's condition. This inscription, states Thapar, could suggest that instead of destruction it may have been a desecration because the temple seems to have been repaired quickly within twelve years and was an active pilgrimage site by 1038.</p>
                            <img src={img1869} alt="" className="h-[250px] w-[300px] my-5" />
                            <p>The raid of 1026 by Mahmud is confirmed by the 11th-century Persian historian Al-Biruni, who worked in the court of Mahmud, who accompanied Mahmud's troops between 1017 and 1030 CE on some occasions, and who lived in the northwest Indian subcontinent region – over regular intervals, though not continuously.[44] The invasion of Somnath site in 1026 CE is also confirmed by other Islamic historians such as Gardizi, Ibn Zafir and Ibn al-Athir. However, two Persian sources – one by adh-Dhahabi and other by al-Yafi'i – state it as 1027 CE, which is likely incorrect and late by a year, according to Khan – a scholar known for his studies on Al-Biruni and other Persian historians.[45] According to Al-Biruni:</p>
                            <p>The location of the Somnath temple was a little less than three miles west of the mouth of the river Sarasvati. The temple was situated on the coast of the Indian ocean so that at the time of flow the idol was bathed by its water. Thus that moon was perpetually occupied in bathing the idol and serving it."</p>
                            <p>Al-Biruni states that Mahmud destroyed the Somnath temple. He states Mahmud's motives as, "raids undertaken with a view to plunder and to satisfy the righteous iconoclasm of a true Muslim... [he] returned to Ghazna laden with costly spoils from the Hindu temples." Al-Biruni obliquely criticizes these raids for "ruining the prosperity" of India, creating antagonism among the Hindus for "all foreigners", and triggering an exodus of scholars of Hindu sciences far away from regions "conquered by us".[46][47] Mahmud launched many plunder campaigns into India, including one that included the sack of Somnath temple.</p>
                            <p>According to Jamal Malik – a South Asian history and Islamic Studies scholar, "the destruction of Somnath temple, a well known place of pilgrimage in Gujarat in 1026, played a major role in creating Mahmud as an "icon of Islam", the sack of this temple became "a crucial topic in Persian stories of Islamic iconoclasm".[49] Many Muslim historians and scholars in and after the 11th-century included the destruction of Somnath as a righteous exemplary deed in their publications. It inspired the Persian side with a cultural memory of Somnath's destruction through "epics of conquest", while to the Hindu side, Somnath inspired tales of recovery, rebuilding and "epics of resistance".[49] These tales and chronicles in Persia elevated Mahmud as "the exemplary hero and Islamic warrior for the Muslims", states Malik, while in India Mahmud emerged as the exemplary "arch-enemy".</p>
                            <p>Powerful legends with intricate detail developed in the Turko-Persian literature regarding Mahmud's raid,[50] which "electrified" the Muslim world according to scholar Meenakshi Jain.[51] According to historian Cynthia Talbot, a later tradition states that "50,000 devotees lost their lives in trying to stop Mahmud" during his sack of Somnath temple.[52] According to Thapar, the "50000 killed" is a boastful claim that is "constantly reiterated" in Muslim texts, and becomes a "formulaic" figure of deaths to help highlight "Mahmud’s legitimacy in the eyes of established Islam".</p>
                            <p>Kumarapala (r. 1143–72) rebuilt the Somnath temple in "excellent stone and studded it with jewels," according to an inscription in 1169. He replaced a decaying wooden temple.</p>
                            <p>During its 1299 invasion of Gujarat, Alauddin Khalji's army, led by Ulugh Khan, defeated the Vaghela king Karna, and sacked the Somnath temple.[56][57] Legends in the later texts Kanhadade Prabandha (15th century) and Nainsi ri Khyat (17th century) state that the Jalore ruler Kanhadadeva later recovered the Somnath idol and freed the Hindu prisoners, after an attack on the Delhi army near Jalore.[58] However, other sources state that the idol was taken to Delhi, where it was thrown to be trampled under the feet of Muslims.[59] These sources include the contemporary and near-contemporary texts including Amir Khusrau's Khazainul-Futuh, Ziauddin Barani's Tarikh-i-Firuz Shahi and Jinaprabha Suri's Vividha-tirtha-kalpa. It is possible that the story of Kanhadadeva's rescue of the Somnath idol is a fabrication by the later writers. Alternatively, it is possible that the Khalji army was taking multiple idols to Delhi, and Kanhadadeva's army retrieved one of them.</p>
                            <p>The temple was rebuilt by Mahipala I, the Chudasama king of Saurashtra in 1308 and the lingam was installed by his son Khengara sometime between 1331 and 1351.[61] As late as the 14th century, Gujarati Muslim pilgrims were noted by Amir Khusrow to stop at that temple to pay their respects before departing for the Hajj pilgrimage.[62] In 1395, the temple was destroyed for the third time by Zafar Khan, the last governor of Gujarat under the Delhi Sultanate and later founder of Gujarat Sultanate.[63] In 1451, it was desecrated by Mahmud Begada, the Sultan of Gujarat.</p>
                            <p>By 1665, the temple, one of many, was ordered to be destroyed by Mughal emperor Aurangzeb.[65] In 1702, he ordered that if Hindus revived worship there, it should be demolished completely.</p>
                        </div>
                        <div>
                            <h1 className="text-xl font-bold">British Raj</h1>
                            <p>In 1842, Edward Law, 1st Earl of Ellenborough issued his Proclamation of the Gates, in which he ordered the British army in Afghanistan to return via Ghazni and bring back to India the sandalwood gates from the tomb of Mahmud of Ghazni in Ghazni, Afghanistan. These were believed to have been taken by Mahmud from Somnath. Under Ellenborough's instruction, General William Nott removed the gates in September 1842. A whole sepoy regiment, the 6th Jat Light Infantry, was detailed to carry the gates back to India in triumph. However, on arrival, they were found not to be of Gujarati or Indian design, and not of Sandalwood, but of Deodar wood (native to Ghazni) and therefore not authentic to Somnath.They were placed in the arsenal store-room of the Agra Fort where they still lie to the present day.[70][71] There was a debate in the House of Commons in London in 1843 on the question of the gates of the temple and Ellenbourough's role in the affair.After much crossfire between the British Government and the opposition, all of the facts as we know them were laid out.</p>
                            <p>In the 19th century novel The Moonstone by Wilkie Collins, the diamond of the title is presumed to have been stolen from the temple at Somnath and, according to the historian Romila Thapar, reflects the interest aroused in Britain by the gates. Her 2004 book on Somnath examines the evolution of the historiographies about the legendary Gujarat temple.</p>
                        </div>
                        <div>
                            <h1 className="text-xl font-bold">Reconstruction during 1950–1951</h1>
                            <p>Before independence, Veraval was part of the Junagadh State, whose ruler had acceded to Pakistan in 1947. India contested the accession and annexed the state after holding a referendum. India's Deputy Prime Minister Vallabhbhai Patel came to Junagadh on 12 November 1947 to direct the stabilization of the state by the Indian Army, at which time he ordered the reconstruction of the Somnath temple.</p>
                            <p>When Patel, K. M. Munshi and other leaders of the Congress went to Mahatma Gandhi with their proposal to reconstruct the Somnath temple, Gandhi blessed the move but suggested that the funds for the construction should be collected from the public, and the temple should not be funded by the state. He expressed that he was proud to associate himself to the project of renovation of the temple.However, soon both Gandhi and Sardar Patel died, and the task of reconstruction of the temple continued under Munshi, who was the Minister for Food and Civil Supplies, Government of India headed by Prime Minister Jawaharlal Nehru.</p>
                            <p>The ruins were pulled down in October 1950. The mosque present at that site was shifted few kilometres away by using construction vehicles.On 11 May 1951, Rajendra Prasad, the first President of the Republic of India, invited by K M Munshi, performed the installation ceremony for the temple.</p>
                        </div>
                        <div>
                            <h1 className="text-xl font-bold">Temple architecture</h1>
                            <p className="text-sm font-bold my-3">Pre-11th century temple</p>
                            <p>The floor plan and ruins of a pre-1000 CE temple were unearthed during the archaeological excavations led by B.K. Thapar. Most of the temple is lost, but the remains of the foundation, the lower structure as well as pieces of the temple ruins suggest an "exquisitely carved, rich" temple. According to Dhaky – a scholar of Indian temple architecture, this is the earliest known version of the Somnath temple. It was, what historic Sanskrit vastu sastra texts call the tri-anga sandhara prasada. Its garbhagriha (sanctum) was connected to a mukhamandapa (entrance hall) and gudhamandapa.</p>
                            <p>The temple opened to the east. The stylobate of this destroyed temple had two parts: the 3 feet high pitha-socle and the vedibandha-podium. The pitha had a tall bhitta, joined to the jadyakumbha, ornamented with what Dhaky calls "crisp and charming foliage pattern". The kumbha of the Vedibandha had a Surasenaka with a niche that contained the figure of Lakulisa – this evidence affirms that the lost temple was a Shiva temple.</p>
                            <p>The excavations yielded pieces of one at the western end, which suggests that the kumbhas were aligned to the entire wall. Above the kalaga moulding was an antarapatta, states Dhaky, but no information is available to determine its design or ornamentation. The surviving fragment of the kapotapali that was discovered suggests that at "intervals, it was decorated with contra-posed half thakaras, with large, elegant, and carefully shaped gagarakas in suspension graced the lower edge of the kapotapali", states Dhaky.[80] The garbhagriha had a vedibandha, possibly with a two-layered jangha with images on the main face showing the influence of the late Maha-Maru style. Another fragment found had a "beautifully moulded rounded pillarette and a ribbed khuraccadya-awning topped the khattaka".</p>
                            <p>The mukhachatuski, states Dhaky, likely broke and fell immediately after the destructive hit by Mahmud's troops. These fragments suffered no further erosion or damage one would normally expect, likely because it was left in the foundation pit of the new Somnath temple that was rebuilt quickly after Mahmud left. The "quality of craftsmanship" in these fragments is "indeed high", the carvings of the lost temple were "rich and exquisite", states Dhaky. Further, a few pieces have an inscription fragment in the 10th-century characters – which suggests that this part of the temple or the entire temple was built in the 10th-century.</p>
                            <h1 className="text-sm font-bold my-3">19th-century ruined Somnath temple partly converted into mosque</h1>
                            <p>The efforts of colonial era archaeologists, photographers and surveyors have yielded several reports on the architecture and arts seen at the Somnath temple ruins in the 19th century.The earliest survey reports of Somnath temple and the condition of the Somanatha-Patan-Veraval town in the 19th-century were published between 1830 and 1850 by British officers and scholars. Alexander Burnes surveyed the site in 1830, calling Somnath site as "far-famed temple and city". He wrote:</p>
                            <p>The great temple of Somnath stands on a rising ground on the north-west side of Pattan, inside the walls, and is only separated by them from the sea. It may be scen from a distance of twenty-five miles. It is a massy stone building, evidently of some antiquity. Unlike Hindu temples gencrally, it consists of three domes, the first of which forms the roof of the entrance, the second is the interior of the temple, the third was the sanctum sanctorum, wherein were deposited the riches of Hindi devotion. The two external domes are diminutive: the central one has an elevation of more than thirty feet, tapering to the summit in fourteen steps, and is about forty feet in diameter. It is perfect, but the images which have once adorned both the interior and exterior of the building are mutilated, and the black polished stones which formed its floor have been removed by the citizens for less pious purposes. Two marble slabs, with sentences from the Koran, and inscriptions regarding Mangrol Isa, point out where that Mohammedan worthy rests. They arc on the western side of the city, and the place is still frequented by the devout Moslem. Near it is a cupola, supported on pillars, to mark the grave of the sultan's cashkeeper, with many others; and the whole city is encircled by the remains of mosques, and one vast cemetery, ‘The field of battle, where the “infidels” were conquered, is also pointed out, and the massy walls, excavated ditch, paved streets, and squared-stone buildings of Pattan itself, proclaim its former greatness. At present the city is a perfect ruin, its houses are nearly unoccupied and but for a new and substantial temple, erected to house the god of Somnath by that wonderful woman, Ahalya Bai, the wife of Holkar.</p>
                            <p>He states that the site shows how the temple had been changed into a Muslim structure with arch, these sections had been reconstructed with "mutilated pieces of the temple's exterior" and "inverted Hindu images". Such modifications in the dilapidated Somnath temple to make it into a "Mohammedan sanctuary", states Burnes, is "proof of Mohammedan devastation" of this site.Burnes also summarized some of the mythologies he heard, the bitter communal sentiments and accusations, as well as the statements by garrisoned "Arabs of the Junagar [Junagadh] chief" about their victories in this "infidel land".</p>
                            <p>The survey report of Captain Postans was published in 1846.  He states: Pattan, and all the part of the country wherein it is situated, is now under a Mohamedan ruler, the Nawab of Junagadh, and the city itself offers the most curious specimen of any I have ever seen of its original Hindu character, preserved throughout its walls, gates, and buildings, despite Mohammedan innovations and a studied attempt to obliterate the traces of paganism ; even the very musjids, which are here and there encountered in the town, have been raised by materials from the sacred edifices of the conquered, or, as it is said by the historians of Sindh, “the true believers turned the temples of the idol worshippers into places of prayer.” Old Pattan is to this day a Hindu city in all but its inhabitants—perhaps one of the most interesting historical spots in Western India.Somnath assumed the appearance it now presents, of a temple evidently of pagan original altered by the introduction of a Mohammedan style of architecture in various portions, but leaving its general plan and minor features unmolested.The temple consists of one large hall in an oblong form, from one end of which proceeds a small square chamber, or sanctum. The centre of the hall is occupied by a noble dome over an octagon of eight arches; the remainder of the roof terraced and supported by numerous pillars. There are three éntrances. The sides of the building face to the cardinal points, and the principal entrance appears to be on the eastern side. These doorways ave unusually high and wide, in the Pyramidal or Egyptian form, decreasing towards the top; they add much to the effect of the building. Internally, the whole presents a scene of complete destruction; the pavement is everywhere covered with heaps of stones and rubbish; the facings of the walls, capitals of the pillars, in short, every portion possessing anything approaching to ornament, having been defaced or removed, (if not by Mahmud, by those who subsequently converted this temple into its present semi-Mohammedan appearance).Externally the whole of the buildings are most elaborately carved and ornamented with figures, single and in groups of various dimensions, Many of them appear to have been of some size; but so laboriously was the work of mutilation carried on here, that of the larger figures scarcely a trunk has been left, whilst few even of the most minute remain uninjured. The western side is the most perfect: here the pillars and ornaments are in excellent preservation. The front entrance is ornamented with a portico, and surmounted by two slender minarets ornaments so much in the Mohammedan style, that they, as well as the domes, have evidently been added to the original building.</p>
                            <p>A more detailed survey report of Somnath temple ruins was published in 1931 by Henry Cousens.Cousens states that the Somnath temple is dear to the Hindu consciousness, its history and lost splendor remembered by them, and no other temple in Western India is "so famous in the annals of Hinduism as the temple of Somanatha at Somanatha-Pattan". The Hindu pilgrims walk to the ruins here and visit it along with their pilgrimage to Dwarka, Gujarat, though it has been reduced to a 19th-century site of gloom, full of "ruins and graves".His survey report states:</p>
                            <p>The old temple of Somanatha is situated in the town, and stands upon the shore towards its eastern end, being separated from the sea by a heavily built retaining wall which prevents the former from washing away the ground around the foundations of the shrine. Little now remains of the walls of the temple; they have been, in great measure, rebuilt and patched with rubble to convert the building into a mosque. The great dome, indeed the whole roof and the stumpy minars, one of which remains above the front entrance, are portions of the Muhammadan additions.One fact alone shows that the temple was built on a large scale, and that is the presence in its basement of the asvathara or horse-moulding. It was probably about the same size, in plan, as the Rudra Mala at Siddhapur, being, in length, about 140 feet over all. [...] The walls, or, at least, the outer casing of them, having in great part fallen, there is revealed, in several places, the finished masonry and mouldings of the basement of an older temple, which appears not to have been altogether removed when the temple, we now see, was built, portions of this older temple being apparently left in situ to form the heart and core of the later masonry.For several reasons, I have come to the conclusion that the ruined temple, as it now stands, save for the Muhammadan additions, is a remnant of the temple built by Kumarapala, king of Gujarat, about AD 1169.</p>
                        </div>
                        <div>
                            <h1 className="text-xl font-bold">Present temple</h1>
                            <p>The present temple is a Māru-Gurjara architecture (also called Chaulukya or Solanki style) temple. It has a "Kailash Mahameru Prasad" form, and reflects the skill of the Sompura Salats, one of Gujarat's master masons.</p>
                            <p>The architect of the new Somnath temple was Prabhashankarbhai Oghadbhai Sompura, who worked on recovering and integrating the old recoverable parts with the new design in the late 1940s and early 1950s. The new Somnath temple is intricately carved, two level temple with pillared mandapa and 212 relief panels.</p>
                            <p>The temple's śikhara, or main spire, is 15 metres (49 ft) in height above the sanctum, and it has an 8.2-metre-tall flag pole at the top.[86] According to Ananda Coomaraswamy – an art and architecture historian, the earlier Somnath temple ruin followed the Solanki-style, which is Nagara architecture inspired by the Vesara ideas found in Western regions of India.</p>
                        </div>
                        <div>
                            <h1 className="text-xl font-bold">Artwork</h1>
                            <p>The rebuilt temple as found in the ruined form in the 19th-century and the current temple used recovered parts of previous temple with significant artwork. The new temple has added and integrated the new panels with a few old ones, the color of the stone distinguishing the two. The panels and pillars with historic artwork were and are found in the south and southwest side of the Somnath temple.</p>
                            <p>In general, the reliefs and sculpture is mutilated, to the point that it is difficult for most to "identify the few images that remain" on panels, states Cousens.[89] An original Nataraja (Tandava Shiva), albeit with chopped arms and defaced, can be seen on the south side. A mutilated Nandi is to the right. To the left of this are traces of Shiva-Parvati, with the goddess seated in his lap.[89] Towards the north-east corner, portions of panels in a band similar to Ramayana scenes in historic Hindu temples can be traced. Sections can be seen with "beautiful vertical mouldings, on either side of the main front doorway", states Cousens, and this suggests that the destroyed temple was "exceedingly richly carved". The temple likely had a galaxy of Vedic and Puranic deities, as one of the partially surviving relief shows Surya's iconography – two lotuses in his hand.</p>
                            <p>The older temple featured an open plan, with great windows that allow light into the mandapa and circumambulation passage. The intricate and detailed artwork inside and on the pillars of Somnath temple were quite similar to those found in the Luna Vasahi temple at Mount Abu.</p>
                        </div>
                        <div>
                            <h1 className="text-xl font-bold">Tirtha and festivals</h1>
                            <p>The Somnath-Prabhasa tirtha has been one of the revered tirtha (pilgrimage) site for the Hindus. It is the famed Prabhasa site found in Brahmi script inscriptions in Maharashtra sites.It is mentioned in the poems of Kalidasa.The new temple is the top pilgrimage site in Gujarat along with Dwarka.</p>
                        </div>
                        <div>
                            <h1 className="text-xl font-bold">Archaeological studies</h1>
                            <p>The Somnath temple site and coastline has been excavated for archaeological evidence by Indian teams. The first major excavation was completed in 1950–51 just before the Somnath temple was reconstructed. It was led by B. K. Thapar, one of the Director General of Archaeological Survey of India, and a report published. This Thapar study yielded direct and substantial evidence of a 10th-century or earlier large temple.B. K. Thapar estimated the older temple to be from the 9th-century, while Dhaky states to more likely from the 10th-century, i.e. from 960 to 973 CE.The Thapar study also found artifacts and ruins with ancient scripts such as Brahmi and later scripts such as proto-Nagari and Nagari, thus confirming the antiquity of Somnath-Patan through at least much of the 1st-millennium.</p>
                            <p>A few Somnath-Patan sites around the Somnath temple was excavated in the 1970s, led by M. K. Dhavalikar and Z. D. Ansari. They dug deeper at several locations, reported evidence of five periods of human settlement. In 1992, M. K. Dhavalikar and Gregory Possehl – an archaeologist known for his Indus Valley studies, reported their analysis of archaeological discoveries from Prabhas-Patan. According to them, the Somnath site shows evidence of ancient human settlement, from pre-2nd millennium BCE period. They date one period to "pre-Harappan phase". However, these discoveries are all ceramics, wares and jewelry (amulet), and they found no ancient "temple parts".[94] According to Charles Herman's critical review, the evidence available so far does not allow any direct inferences about the society and culture in pre-1st millennium BCE era, but there is persuasive evidence that Prabhas-Patan was an early Harappan site with sedentary farming and cattle keeping and it is in the same league of significance as the Dholavira (Kutch) and Rojdi (Sorath-Harappan) archaeological sites. Further, the Prabhas-Patan mounds that have been excavated show evidence of continued post-Harappan settlement (c. 2000– 1800 BCE) along with several other Saurashtra sites. According to Herman, the archaeological excavations in Prabhas-Patan and Saurashtra region have been too few to make systematic conclusions.</p>
                        </div>
                        <div>
                            <h1 className="text-xl font-bold">Legacy</h1>
                            <p className="text-sm font-bold my-3">Iran</p>
                            <p>The Somnath temple has inspired different narratives and legacies, for some a symbol of blessed conquest and victories, for some a symbol of fanatical intolerance and persecution. After the 1026 sack of the Somnath temple, states Mehrdad Shokoohy, the "sack of Somnath was not just yet another campaign of a medieval Sultan confined to histories, but a symbol of the revival of Iranian identity boosted by religious zeal, which was to echo in literature and folklore" for nearly one thousand years. The destruction of the Somnath temple – called Sūmanāt in Persian literature, and the killing of the infidels has been portrayed as a celebrated event in numerous versions of history, stories and poems found in Persia written over the centuries. The Persian literature has made mythical ahistorical connections of Somnath to Manat.[96] The destruction of both has been celebrated by the Islamic scholars and elites.</p>
                            <p className="text-sm font-bold my-3" >India</p>
                            <p>On the Indian side, the Somnath temple has been more than another house of worship. For Hindus, particularly Hindu nationalists, it is a question of their heritage, their sense of sacred time and space, states Peter van der Veer.[99] Its history raises questions of tolerance and spiritual values to expect, and of a symbol of fanaticism and foreign oppression. The Somnath temple has been leveraged to revisit India's history and agitate over its sacred spaces including contested sites such as Ayodhya.[99] Mahmud and Aurangzeb along with the ideology that inspired them are remembered as enemies of the ancient Hindu nation. They are asserted as two historical facts, the former as the first and the latter as the last systematic destroyers of Somnath temple.</p>
                            <p>The Somnath temple was used as a cultural symbol and the starting point for a Rath yatra (chariot journey), states K.N. Pannikkar, by Lal Krishna Advani to begin his Ayodhya campaign in 1990.[100][101] According to Donald Smith, the reconstruction efforts in the 1950s was not about restoring an ancient architecture, rather the Somnath temple was of religious significance. The rebuilding was a symbol, it was Hindu repudiation of almost a thousand years of Muslim domination, oppression, and reassertion of a safe haven for Hindus in post-partitioned India.</p>
                            <p>The reconstructed Somnath temple has been the preferred pilgrimage site for Hindus in Gujarat, often combined with a pilgrimage to Dwarka. The site attracts Hindus from all over India, states David Sopher.</p>
                            <p className="text-sm font-bold my-3">Pakistan and West Asia</p>
                            <p>In the modern era textbooks of Pakistan, the sack of Somnath temple is praised and the campaign of Sultan Mahmud of Ghaznavi is glorified as a "champion of Islam". According to Syed Zaidi – a scholar of Islamist Militancy, a school book in Pakistan titled Our World portrays Somnath temple as a "place where all the Hindu rajas used to get together" and think about "fighting the Muslims". Mahmud went to this temple and "blew the idol in pieces" and "this success was a source of happiness for the whole Muslim world".[103] Another textbook for Pakistan's Middle School repeats a similar narrative, teaching its students that the Somnath temple was not really a Hindu temple but a political center. According to Ashok Behuria and Mohammad Shehzad, the Somnath legacy is narrated in this textbook as, "according to most historians Mahmud invaded India seventeen times to crush the power of the Hindu Rajas and Maharajas who were always busy planning conspiracies against him ... After the fall of Punjab, the Hindus assembled at Somnath — which was more of a political centre than a temple — to plan a big war against Mahmud. He took all the Rajas and Maharajas by surprise when he attacked Somnath and crushed the Hindu headquarter of political intrigue. With the destruction of Somnath he broke the backbone of the Hindus in the region and thus had no need to attack India again".</p>
                            <p>In Islamic State nationalist literature of the modern era, Sultan Mahmud campaign in the 11th-century has been glorified as a historic "jihad against non-Muslims", his motive in destroying Somnath temple is described as "not driven by worldly gain [wealth]", but because he wanted to "end the worship of idols".</p>
                            <p className="text-sm font-bold my-3">Afghanistan</p>
                            <p>In 1842, during the First Anglo-Afghan war, the Governor-General of India Lord Ellenborough ordered his troops to bring the wooden gates from the tomb of Mahmud of Ghazni in Ghazni, Afghanistan back to India; it was believed Mahmud had taken them from Somnath Temple. However, there was nor there is any evidence that Somnath temple or its site ever had any wooden gates. Nor is there any evidence that Mahmud or later conquerors ever took any gates from Prabhas-Patan region as a part of the plunder. This order has been called the Proclamation of the Gates.The order, states Thapar, is best seen as an example of how "colonial intervention in India" was viewed in the 1840s.</p>
                        </div>
                    </div>
                )}

                {gujrati && (
                    <div className="flex flex-col space-y-3">
                        <div className="space-y-3">
                            <p>સોમનાથ ગુજરાત રાજ્યમાં સૌરાષ્ટ્રના સાગરકાંઠે આવેલું ભવ્ય મંદિર છે. ભગવાન શિવના ૧૨ પવિત્ર જ્યોતિર્લિંગમાનું પ્રથમ જ્યોતિર્લિગ અહીં સોમનાથમાં છે.[૧] સોમનાથનો ઉલ્લેખ ઋગ્વેદમાં પણ થયો છે. મંદિરની ખ્યાતિથી લલચાઈને લુંટ તથા ધર્માંતરણ કરવાને ઈરાદે આવેલા અનેક વિનાશકારી ઇસ્લામીક આક્રમણકારો સામે સોમનાથનું આ મંદિર અડીખમ રહ્યું છે. મંદિરનો જ્યારે જ્યારે વિનાશ કરવાનો પ્રયત્ન થયો છે, ત્યારે ત્યારે તેને ફરીને બાંધવામાં આવ્યું છે.</p>
                        </div>
                        <div className="space-y-3">
                            <h1 className="text-xl font-bold">દંતકથા</h1>
                            <p>દંતકથા અનુસાર, સોમ એટલે ચંદ્ર ભગવાને સોનાનું, રાવણે ચાંદીનું અને શ્રી કૃષ્ણે ચંદન ના લાકડાનુ મંદિર બાંધ્યું હતું.</p>
                            <p>
                                ચંદ્રદેવને ૨૭ પત્નીઓ હતી જેને આપણે આજે ૨૭ નક્ષત્રોના નામોથી ઓળખીએ છીએ. તે બધી દક્ષ પ્રજાપતિની પુત્રીઓ હતી. તેમાંથી રોહિણી નામવાળી પત્ની સાથે ચંદ્ર સદાય પ્રેમમગ્ન રહેતા. બાકીની ૨૬ પત્નીઓ કે જે સગી બહેનો હતી તે પતિ વિયોગે ઉદાસ રહેવા લાગી. એક દિવસ પિતા દક્ષ દીકરીઓનું દુઃખ જાણીને દુભાયા અને જમાઈ ચંદ્રને આજ્ઞા કરી કે દરેક પત્ની સાથે સરખો પ્રેમભાવ રાખવો. પણ ચંદ્રે વડીલની આજ્ઞા અવગણી. આથી દક્ષરાજે ક્રોધે ભરીને તેમને "ચંદ્ર તારો ક્ષય થાય." એવો શ્રાપ આપ્યો.. આથી પ્રજાપિતા બ્રહ્માની સલાહથી સૌથી પ્રિય પત્ની રોહિણી સાથે ચંદ્રએ આ સ્થળે 'પ્રભા' પાછી મેળવવાની આશા સાથે પ્રભુ શિવનું ધ્યાન કર્યું ને તપસ્યા કરી. તેણે આ ક્ષેત્રમાં શિવજીની મહામૃત્યુંજય મંત્રથી પૂજા કરી હતી.તપથી પ્રસન્ન થયેલા શિવ શંકરના અનુગ્રહથી ચંદ્રનો શ્રાપમાંથી આંશિક છૂટકારો થયો. ત્યારથી શિવજીની કૃપાથી ૧૫ દિવસ સુધી વધતો (સૂદ અથવા કૃષ્ણ પક્ષ) અને પછી ૧૫ દિવસ ઘટતો (વદ અથવા શુકલ પક્ષ) ચંદ્ર થાય છે.
                            </p>
                        </div>
                        <div className="space-y-3">
                            <h1 className="text-xl font-bold">ઇતિહાસ</h1>
                            <p>મધ્ય કાલીન યુગમાં સોમનાથનું પહેલું મંદિર ૨૦૦૦ વર્ષ પહેલાં અસ્તિત્વમાં આવ્યું હોવાનું કહેવાય છે. ઇ.સ. ૬૪૯ની સાલમાં વલ્લભીવંશના શાસક રાજા મૈત્રકે પહેલાં મંદિરનો જીર્ણોદ્ધાર કરી તેના સ્થાને બીજું મંદિર બનાવ્યું. આ સમય સને ૪૮૭ થી ૭૬૭ સુધીનો ગણાય છે. પરમારોના એક શિલાલેખ મુજબ માળવાના ભોજ પરમારે અહીં મંદિર બંધાવ્યું હતું. આ મંદિર ૧૩ માળ ઊંચું હતું અને મંદિરના દ્વાર હીરાજડિત હતા. તેના ઉપર ૧૪ સુવર્ણ કળશો વિરાજમાન હતા. તેની ઉંચે ફરકતી ધજાથી નાવિકો તેને સોમનાથનું મંદિર પિછાણી તે તરફ વહાણો હંકારતા. ઈ.સ. ૭૫૫ માં વલ્લભી સામ્રાજ્યના પતન સાથે આરબ આક્રમકોએ સોમનાથનું પતન કર્યું. સિંધના અરબ શાસક જૂનાયદે તેની સેના લઈ મંદિર પર હુમલો કરી મંદિરનો નાશ કર્યો હતો. પ્રતિહાર રાજા નાગ ભટ્ટ બીજાએ ૮૧૫માં ત્રીજી વખત લાલ પથ્થર (રેતીયો પથ્થર) વાપરી મંદિરનું નિર્માણ કર્યું.</p>
                            <p>૧૦૨૫ની સાલમાં મહંમદ (કે મહમૂદ) ગઝનવીએ પ્રભાસનો મજબૂત કિલ્લો હિંદુઓ સાથેના ૮ દિવસ ચાલેલા લોહીયાળ જંગ પછી તોડ્યો. રાજા ભીમદેવ પહેલા હાર્યા. ૫૦,૦૦૦ હિન્દુઓની કતલ થઇ. તેણે મહાદેવજીની પાંચ ગજ ઉંચી અને બે ગજ પહોળી મૂર્તિ તોડવા માંડી ત્યારે શિવભક્ત ભૂદેવોએ તેને તે સમયે પાંચ કરોડ રૂપિયા આપવાની તૈયારી બતાવી. પણ તેણે કહ્યું: રૂપિયા લેવા કરતાં મને મૂર્તિ ભાંગવામાં વધારે મજા પડે છે! અને આખરે સોમનાથ લૂંટાયું અને તેણે સળગાવીને તેનો વિનાશ કરવામાં આવ્યો. શિવલિંગના ટુકડે-ટુકડા કરવામાં આવ્યા. એટલું જ નહિ, તે શિવલિંગના ટુકડાઓ તે પોતાની સાથે પાછો ગઝની લઇ ગયો અને ત્યાંના એક મસ્જિદના પ્રવેશદ્વારના પગથિયાંની નીચે તેમને દાટી દીધા કે જેથી મુસલમાનો હંમેશા એમના ઉપર પગ મૂકીને [અપમાનિત કરીને] મસ્જીદમાં પ્રવેશી શકે. મહમૂદને એક જ માસમાં રાજા પરમદેવે ત્યાંથી ભગાડ્યો.</p>
                            <p>૧૦૨૬-૧૦૪૨ના સમયમાં માળવાના પરમાર રાજા ભોજ તથા અણહિલવાડ પાટણના સોલંકી રાજા ભીમદેવે ચોથા મંદિરનું નિર્માણ કર્યું. તે જીર્ણ થતાં સમ્રાટ કુમારપાળે સને ૧૧૬૯માં આ મંદિરની રચના પુન: કરાવીને ફરીથી મંદિરની મહિમાનો અને જાહોજલાલીનો યુગ શરૂ કર્યો. આ પછી ૧૨૦ વર્ષે, સને ૧૨૯૯ની સાલમાં જ્યારે દિલ્લી સલ્તનતે ગુજરાતનો કબજો કર્યો ત્યારે અલ્લાઉદ્દીન ખીલજીના સેનાપતિ ઉલુઘખાને મૂર્તિના ટુકડે ટુકડા કર્યા અને ગાડામાં ભરીને તે દિલ્હી લઇ ગયો. [૪] સોમનાથનો વિનાશ કરવામાં આવ્યો.[૫] અગિયારમી સદીમાં આ વિનાશ પહેલા સોમનાથની સમૃદ્ધિ કેટલી વિપુલ હતી તેનો ઉલ્લેખ મળે છે કે સ્થાનિક રાજાઓએ મંદિરના નિભાવ માટે ૧૦,૦૦૦ ગામડાં અર્પણ કર્યા હતા. આ પવિત્ર સ્થળમાં ૨૦૦ મણ વજનની સાંકળો ઉપર સોનાની ઘંટડીઓ ઝૂલતી હતી, જેના દ્વારા શિવપૂજાના સમયની જાહેરાત કરાતી. ૫૬ જેટલા સાગના વિરાટ સ્તંભો ઉપર આ મંદિર ઉભું હતું. સેંકડો નટ-નટીઓ નૃત્ય કરી ભગવાન શિવને રીઝવતા. થાંભલે થાંભલે હિન્દુસ્તાનના રાજવીઓના નામ, ઈતિહાસ અને ખજાના ભર્યા હતા. માત્ર અને માત્ર ગંગાજીના પાણીથી જ અહીં પૂજન થતું. ભોયરામાં રત્નો અને સોનાના ભંડારો હતા. પરંતુ મૂર્તિ ગઈ, લૂંટ થઇ. પછી ફરી મંદિર વેરાન બની ગયું. એ પછી રા'નવઘણ ચોથાએ માત્ર લિંગની પ્રતિષ્ઠા કરી અને રાજા મહિપાળ દેવે સને ૧૩૦૮ અને ૧૩૨૫ વચ્ચે સમગ્ર મંદિરનો જીર્ણોદ્ધાર કર્યો. સને ૧૩૪૮ માં રાજા રા'ખેંગાર ચોથાએ સોમનાથમાં રહેતા મુસ્લિમ હાકેમને હાંકી કાઢ્યો. પરંતુ માત્ર ૭૦ જ વર્ષ પછી સને ૧૩૯૪-૯૫માં ગુજરાતના ધર્માંધ સુલતાન મુઝ્ઝફરખાન બીજાએ તેનો ફરીથી મૂર્તિ સહિત વિનાશ કર્યો. [૬] મંદિરમાં મસ્જિદ બનાવી. મૌલવીઓ અને કાઝીઓ રાખ્યા. સોમનાથ ફરી એક વાર ભ્રષ્ટ કરાયું. લોકોએ થોડા જ વર્ષોમાં ફરી નવી મૂર્તિ પધરાવી. સને ૧૪૧૪ માં અમદાવાદનો સ્થાપક અહમદશાહ પહેલો મૂર્તિ ઉઠાવીને લઇ ગયો અને સોમનાથ પાયમાલ કરી મૂક્યું. એ પછી સને ૧૪૫૧માં રા'માંડલિકે મુસ્લિમ થાણા ઉઠાવી પુન: મંદિર પ્રતિષ્ઠા કરી. પરંતુ, ૧૫મી સદીમાં મહમદ બેગડો (સને ૧૪૫૯ થી ૧૫૧૧) ચઢી આવ્યો. તેણે મંદિરને મસ્જીદમાં ફેરવી નાખ્યું. ઈ.સ. ૧૫૬૦માં અકબરના સમયમાં મંદિર હિન્દુઓને પાછું મળ્યું અને પાછો પુનરુદ્ધાર થયો. ત્યાર બાદ શાંતિનો સમય ૨૦૦ વર્ષ સુધી ચાલ્યો. એ પછી ઔરંગઝેબ અને માંગરોળના શેખે મંદિરની અવદશા કરી. ૧૭૦૬ની સાલમાં મોગલ શાસક ઔરંગઝેબે મંદિરના સર્વનાશનો હુકમ કર્યો અને ફરીથી મંદિર તોડી પાડ્યું.[૭][૮] ભારત દેશ સ્વતંત્ર થયો તે પહેલાનો મંદિરનો છેલ્લો જીર્ણોદ્ધાર સને ૧૭૮૭ માં મહારાણી અહલ્યાબાઈએ કરાવ્યો.</p>
                        </div>
                        <div className="space-y-3">
                            <h1 className="text-xl font-bold">સ્વતંત્ર ભારતમાં પુન:નિર્માણ</h1>
                            <p>ભારતના લોખંડી પુરૂષ તથા પહેલા નાયબ વડાપ્રધાન સરદાર વલ્લભભાઈ પટેલે નવેમ્બર ૧૩, ૧૯૪૭નાં રોજ મંદિરનું પુનઃનિર્માણ કરવાની પ્રતિજ્ઞા કરી. આજનાં સોમનાથ મંદિરનું તેની મૂળ જગ્યા પર સાતમી વખત નિર્માણ થયું. ૧૧ મે ૧૯૫૧ના દિવસે કે જયારે મંદિરની પ્રાણ-પ્રતિષ્ઠા થઇ ત્યારે તત્કાલીન ભારતના પ્રથમ રાષ્ટ્રપતિ ડૉ. રાજેન્દ્ર પ્રસાદે જ્યોતિર્લિંગની પ્રતિષ્ઠાન કરવાની વિધી કરી ત્યારે કહ્યું કે, "સોમનાથનું આ મંદિર વિનાશ પર નિર્માણના વિજયનું પ્રતિક છે". ૧૦૧ તોપોનું મહાદેવજીને સન્માન અપાયું. નૌકાદળે સાગરમાંથી તોપો ફોડી. સેંકડો બ્રાહ્મણોએ વેદઘોષ કરીને પ્રતિષ્ઠા કરી.શ્રી સોમનાથ ટ્રસ્ટ હેઠળ મંદિરનું નિર્માણ થયું છે અને આ ટ્રસ્ટ હવે મંદિરની દેખરેખ કરે છે. સરદાર પટેલ આ ટ્રસ્ટનાં પ્રથમ ચેરમેન હતાં અને ભુતપૂર્વ મુખ્યમંત્રી કેશુભાઈ પટેલ પણ આ પદે રહ્યા હતા.</p>
                            <p>ચાલુક્ય શૈલીથી બાંધેલું આજનુ "કૈલાશ મહામેરુ પ્રાસાદ મંદિર" ગુજરાતના સોમપુરા કારીગરોની કલાનું અદભૂત પ્રદર્શન કરે છે. મૂળ સોમનાથ મંદિર ત્રિકૂટાચલ પ્રકારનું હતું. છેલ્લા ૮૦૦ વર્ષમાં આ પ્રકારનું નિર્માણ થયું નથી.[સંદર્ભ આપો] સાગર કિનારે આવેલા સંસ્કૃતમાં લખેલા શિલાલેખ પ્રમાણે, મંદિર તથા પૃથ્વીના દક્ષિણ ધૃવની વચ્ચે ફક્ત સમુદ્ર જ આવેલ છે અને કોઈ જમીન નથી.</p>
                        </div>
                    </div>
                )}

                {hindi && (
                    <div className="flex flex-col space-y-3">
                        <div>
                            <p>सोमनाथ मन्दिर भूमण्डल में दक्षिण एशिया स्थित भारतवर्ष के पश्चिमी छोर पर गुजरात नामक प्रदेश स्थित, अत्यन्त प्राचीन व ऐतिहासिक शिव मन्दिर का नाम है। यह भारतीय इतिहास तथा हिन्दुओं के चुनिन्दा और महत्वपूर्ण मन्दिरों में से एक है। इसे आज भी भारत के 12 ज्योतिर्लिंगों में सर्वप्रथम ज्योतिर्लिंग के रूप में माना व जाना जाता है। गुजरात के सौराष्ट्र क्षेत्र के वेरावल बन्दरगाह में स्थित इस मन्दिर के बारे में कहा जाता है कि इसका निर्माण स्वयं चन्द्रदेव ने किया था, जिसका उल्लेख ऋग्वेद में स्पष्ट है।.</p>
                            <p>यह मन्दिर हिन्दू धर्म के उत्थान-पतन के इतिहास का प्रतीक रहा है। अत्यन्त वैभवशाली होने के कारण इतिहास में कई बार यह मंदिर तोड़ा तथा पुनर्निर्मित किया गया। वर्तमान भवन के पुनर्निर्माण का आरम्भ भारत की स्वतन्त्रता के पश्चात् लौहपुरुष सरदार वल्लभ भाई पटेल ने करवाया और पहली दिसम्बर 1955 को भारत के राष्ट्रपति डॉ राजेंद्र प्रसाद जी ने इसे राष्ट्र को समर्पित किया। सोमनाथ मन्दिर विश्व प्रसिद्ध धार्मिक व पर्यटन स्थल है। मन्दिर प्रांगण में रात साढ़े सात से साढ़े आठ बजे तक एक घण्टे का साउण्ड एण्ड लाइट शो चलता है, जिसमें सोमनाथ मन्दिर के इतिहास का बड़ा ही सुन्दर सचित्र वर्णन किया जाता है। लोककथाओं के अनुसार यहीं श्रीकृष्ण ने देहत्याग किया था। इस कारण इस क्षेत्र का और भी महत्त्व बढ़ गया।.</p>
                            <p>सोमनाथजी के मन्दिर की व्यवस्था और संचालन का कार्य सोमनाथ ट्रस्ट के अधीन है। सरकार ने ट्रस्ट को जमीन, बाग-बगीचे देकर आय का प्रबन्ध किया है। यह तीर्थ पितृगणों के श्राद्ध, नारायण बलि आदि कर्मो के लिए भी प्रसिद्ध है। चैत्र, भाद्रपद, कार्तिक माह में यहाँ श्राद्ध करने का विशेष महत्त्व बताया गया है। इन तीन महीनों में यहाँ श्रद्धालुओं की बड़ी भीड़ लगती है। इसके अलावा यहाँ तीन नदियों हिरण, कपिला और सरस्वती का महासंगम होता है। इस त्रिवेणी स्नान का विशेष महत्त्व है।.</p>
                        </div>
                        <div>
                            <h1 className="text-xl font-bold">किंवदन्तियाँ</h1>
                            <p>प्राचीन हिन्दू ग्रन्थों के अनुसार में बताये कथानक के अनुसार सोम अर्थात् चन्द्र ने, दक्षप्रजापति राजा की 27 कन्याओं से विवाह किया था। लेकिन उनमें से रोहिणी नामक अपनी पत्नी को अधिक प्यार व सम्मान दिया कर होते हुए अन्याय को देखकर क्रोध में आकर दक्ष ने चन्द्रदेव को शाप दे दिया कि अब से हर दिन तुम्हारा तेज (काँति, चमक) क्षीण होता रहेगा। फलस्वरूप हर दूसरे दिन चन्द्र का तेज घटने लगा। शाप से विचलित और दु:खी सोम ने भगवान शिव की आराधना शुरू कर दी। अन्ततः शिव प्रसन्न हुए और सोम-चन्द्र के शाप का निवारण किया। सोम के कष्ट को दूर करने वाले प्रभु शिव का स्थापन यहाँ करवाकर उनका नामकरण हुआ "सोमनाथ"।.</p>
                            <p>ऐसी मान्यता है कि श्रीकृष्ण भालुका तीर्थ पर विश्राम कर रहे थे। तब ही शिकारी ने उनके पैर के तलुए में पद्मचिह्न को हिरण की आँख जानकर अनजाने में तीर मारा था। तब ही कृष्ण ने देह त्यागकर यहीं से वैकुण्ठ गमन किया। इस स्थान पर बड़ा ही सुन्दर कृष्ण मन्दिर बना हुआ है।.</p>
                        </div>
                        <div>
                            <h1 className="text-xl font-bold">इतिहास</h1>
                            <p>सर्वप्रथम एक मन्दिर ईसा के पूर्व में अस्तित्व में था जिस जगह पर द्वितीय बार मन्दिर का पुनर्निर्माण सातवीं सदी में वल्लभी के मैत्रक राजाओं ने किया। आठवीं सदी में सिन्ध के अरबी गवर्नर जुनायद ने इसे नष्ट करने के लिए अपनी सेना भेजी। गुर्जर प्रतिहार राजा नागभट्ट ने 815 ईस्वी में इसका तीसरी बार पुनर्निर्माण किया। इस मन्दिर की महिमा और कीर्ति दूर-दूर तक फैली थी। अरब यात्री अल-बरुनी ने अपने यात्रा वृतान्त में इसका विवरण लिखा जिससे प्रभावित हो महमूद ग़ज़नवी ने सन 1025 में कुछ 5,000 साथियों के साथ सोमनाथ मन्दिर पर हमला किया, उसकी सम्पत्ति लूटी और उसे नष्ट कर दिया। 50,000 लोग मन्दिर के अन्दर हाथ जोड़कर पूजा अर्चना कर रहे थे, प्रायः सभी कत्ल कर दिये गये.</p>
                            <p>इसके बाद गुजरात के राजा भीम और मालवा के राजा भोज ने इसका पुनर्निर्माण कराया। सन 1297 में जब दिल्ली सल्तनत ने गुजरात पर क़ब्ज़ा किया तो इसे पाँचवीं बार गिराया गया। मुगल बादशाह औरंगजेब ने इसे पुनः 1706 में गिरा दिया। इस समय जो मंदिर खड़ा है उसे भारत के गृह मन्त्री सरदार वल्लभ भाई पटेल ने बनवाया और पहली दिसम्बर 1955 को भारत के राष्ट्रपति डॉ॰ राजेन्द्र प्रसाद ने इसे राष्ट्र को समर्पित किया।.</p>
                            <p>1948 में प्रभासतीर्थ, 'प्रभास पाटण' के नाम से जाना जाता था। इसी नाम से इसकी तहसील और नगर पालिका थी। यह जूनागढ़ रियासत का मुख्य नगर था। लेकिन 1948 के बाद इसकी तहसील, नगर पालिका और तहसील कचहरी का वेरावल में विलय हो गया। मंदिर का बार-बार खंडन और जीर्णोद्धार होता रहा पर शिवलिंग यथावत रहा। लेकिन सन 1026 में महमूद गजनी ने जो शिवलिंग खण्डित किया, वह यही आदि शिवलिंग था। इसके बाद प्रतिष्ठित किए गए शिवलिंग को 1300 में अलाउद्दीन की सेना ने खण्डित किया। इसके बाद कई बार मन्दिर और शिवलिंग को खण्डित किया गया। बताया जाता है आगरा के किले में रखे देवद्वार सोमनाथ मन्दिर के हैं। महमूद गजनी सन 1026 में लूटपाट के दौरान इन द्वारों को अपने साथ ले गया था।.</p>
                            <p>सोमनाथ मन्दिर के मूल मन्दिर स्थल पर मन्दिर ट्रस्ट द्वारा निर्मित नवीन मन्दिर स्थापित है। राजा कुमार पाल द्वारा इसी स्थान पर अन्तिम मन्दिर बनवाया गया था। सौराष्ट्र के मुख्यमन्त्री उच्छंगराय नवलशंकर ढेबर ने १९ अप्रैल १९४० को यहाँ उत्खनन कराया था। इसके बाद भारत सरकार के पुरातत्व विभाग ने उत्खनन द्वारा प्राप्त ब्रह्मशिला पर शिव का ज्योतिर्लिग स्थापित किया है।.</p>
                        </div>
                        <div>
                            <h1 className="text-xl font-bold">भारत की स्वतन्त्रता के बाद पुनर्निर्माण</h1>
                            <p>सौराष्ट्र के पूर्व राजा दिग्विजय सिंह ने 8 मई 1950 को मन्दिर की आधारशिला रखी तथा ११ मई 1951 को भारत के प्रथम राष्ट्रपति डॉ॰ राजेंद्र प्रसाद ने मन्दिर में ज्योतिर्लिग स्थापित किया।.नवीन सोमनाथ मन्दिर 1962 में पूर्ण निर्मित हो गया। 1970 में जामनगर की राजमाता ने अपने पति की स्मृति में उनके नाम से 'दिग्विजय द्वार' बनवाया। इस द्वार के पास राजमार्ग है और पूर्व गृहमन्त्री सरदार वल्लभ भाई पटेल की प्रतिमा है। सोमनाथ मन्दिर निर्माण में पटेल का बड़ा योगदान रहा।.</p>
                            <p>मन्दिर के दक्षिण में समुद्र के किनारे एक स्तम्भ है। उसके ऊपर एक तीर रखकर संकेत किया गया है कि सोमनाथ मन्दिर और दक्षिण ध्रुव के बीच में पृथ्वी का कोई भूभाग नहीं है (आसमुद्रान्त दक्षिण ध्रुव पर्यंत अबाधितs ज्योतिर्मार्ग)। इस स्तम्भ को 'बाणस्तम्भ' कहते हैं।.मन्दिर के पृष्ठ भाग में स्थित प्राचीन मन्दिर के विषय में मान्यता है कि यह पार्वती जी का मन्दिर है।.</p>
                            <p>जवाहरलाल नेहरू ने सोमनाथ मन्दिर के पुनर्निर्माण के प्रस्ताव का ‘हिन्दू पुनरुत्थानवाद’ कहकर विरोध भी किया। उस समय नेहरू से हुई बहस को कन्हैयालाल मुंशी ने अपनी पुस्तक ‘पिलग्रिमेज टू फ़्रीडम’ में दर्ज किया है। वे लिखते हैं- </p>
                            <p> कैबिनेट की बैठक के अन्त में जवाहरलाल ने मुझे बुलाकर कहा—मुझे सोमनाथ के पुनरुद्धार के लिए किया जा रहा आपका प्रयास पसन्द नहीं आ रहा। यह हिन्दू पुनरुत्थानवाद है। ‘मैंने जवाब दिया कि मैं घर जाकर, जो कुछ भी घटित हुआ है उसके बारे में आपको जानकारी दूँगा.</p>
                            <p>दिसम्बर 1922 में मैं उस भग्न मन्दिर की तीर्थ यात्रा पर निकला। वहाँ पहुँचकर मैंने मन्दिर में भयंकर दुरवस्था देखी—अपवित्र, जला हुआ और ध्वस्त! पर फिर भी वह दृढ़ खड़ा था, मानो हमारे साथ की गई कृतघ्नता और अपमान को न भूलने का सन्देश दे रहा हो। उस दिन सुबह जब मैंने पवित्र सभामण्डप की ओर कदम बढ़ाए तो मन्दिर के खमृभों के भग्नावशेषों और बिखरे पत्थरों को देखकर मेरे अन्दर अपमान की कैसी अग्निशिखा प्रज्जवलित हो उठी थी, मैं बता नहीं सकता।.</p>
                            <p>के.एम. मुंशी आगे लिखते हैं-</p>
                            <p>नवम्बर 1947 के मध्य में सरदार प्रभास पाटन के दौरे पर थे जहाँ उन्होंने मन्दिर का दर्शन किया। एक सार्वजनिक सभा में सरदार ने घोषणा की: ‘नए साल के इस शुभ अवसर पर हमने फैसला किया है कि सोमनाथ का पुनर्निर्माण करना चाहिए। सौराष्ट्र के लोगों को अपना सर्वश्रेष्ठ योगदान देना होगा। यह एक पवित्र कार्य है जिसमें सभी को भाग लेना चाहिए।’ ...कुछ लोगों ने प्राचीन मंदिर के भग्नावशेषों को प्राचीन स्मारक के रूप में संजोकर रखने का सुझाव दिया जिन्हें मृत पत्थर जीवन्त स्वरूप की तुलना में अधिक प्राणवान लगते थे। लेकिन मेरा स्पष्ट मानना था कि सोमनाथ का मन्दिर कोई प्राचीन स्मारक नहीं, बल्कि प्रत्येक भारतीय के हृदय में स्थित पूजा स्थल था जिसका पुनर्निर्माण करने के लिए अखिल राष्ट्र प्रतिबद्ध था।.</p>
                        </div>
                        <div>
                            <h1 className="text-xl font-bold">तीर्थ स्थान और मन्दिर</h1>
                            <p>वेरावल प्रभास क्षेत्र के मध्य में समुद्र के किनारे मन्दिर बने हुए हैं.</p>
                            <p>शशिभूषण मन्दिर, भीड़भंजन गणपति, बाणेश्वर, चंद्रेश्वर-रत्नेश्वर, कपिलेश्वर, रोटलेश्वर, भालुका तीर्थ है। भालकेश्वर, प्रागटेश्वर, पद्म कुण्ड, पाण्डव कूप, द्वारिकानाथ मन्दिर, बालाजी मन्दिर, लक्ष्मीनारायण मन्दिर, रूदे्रश्वर मन्दिर, सूर्य मन्दिर, हिंगलाज गुफा, गीता मन्दिर, बल्लभाचार्य महाप्रभु की 65वीं बैठक के अलावा कई अन्य प्रमुख मन्दिर है।.</p>
                            <p>प्रभास खण्ड में विवरण है कि सोमनाथ मन्दिर के समयकाल में अन्य देव मन्दिर भी थे।.</p>
                            <p>इनमें शिवजी के 135, विष्णु भगवान के 5, देवी के 25, सूर्यदेव के 16, गणेशजी के 5, नाग मन्दिर 1, क्षेत्रपाल मन्दिर 1, कुण्ड 19 और नदियाँ 9 बताई जाती हैं। एक शिलालेख में विवरण है कि महमूद के हमले के बाद इक्कीस मन्दिरों का निर्माण किया गया। सम्भवत: इसके पश्चात भी अनेक मन्दिर बने होंगे।.</p>
                            <p>सोमनाथ से करीब दो सौ किलोमीटर दूरी पर प्रमुख तीर्थ श्रीकृष्ण की द्वारिका है। यहाँ भी प्रतिदिन द्वारिकाधीश के दर्शन के लिए देश-विदेश से हजारों की संख्या में श्रद्धालु आते हैं। यहाँ गोमती नदी है। इसके स्नान का विशेष महत्त्व बताया गया है। इस नदी का जल सूर्योदय पर बढ़ता जाता है और सूर्यास्त पर घटता जाता है, जो सुबह सूरज निकलने से पहले मात्र एक डेढ़ फीट ही रह जाता है।.</p>
                        </div>
                    </div>
                )}

                {image && (
                    <div className="grid grid-cols-3 gap-y-5">
                        <img src={img2} alt="" className="h-[250px] w-[300px]" />
                        <img src={img3} alt="" className="h-[250px] w-[300px]" />
                        <img src={img4} alt="" className="h-[250px] w-[300px]" />
                    </div>
                )}
            </div>
        </>
    );
};

export default Somnath;